In [ ]:
#1. Create a 1D NumPy Array:
Create a 1D NumPy array named temperatures_w1 for Week 1 with the
following values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [ ]:
import numpy as np

temperatures_w1_1d = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1_1d

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperature_w1)

[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]


In [ ]:
#2. Inspection and Properties:
Inspect the shape, data type, and the number of elements in the array.
Inspect the shape of the temperatures_w1 array.

In [ ]:
temperatures_w1_1d.shape

(7,)

In [ ]:
temperatures_w1_1d.dtype

dtype('float64')

In [ ]:
temperatures_w1_1d.size

7

In [ ]:
temperatures_w1.shape

(7,)

In [ ]:
#3. Array Operations:
Convert the temperatures_w1 from Celsius to Fahrenheit using the
formula: Fahrenheit = (Celsius * 9/5) + 32
Find the maximum, minimum, and mean temperatures for the week.

In [ ]:
temperatures_f = (temperatures_w1 * 9/5) + 32
print("Temperatures in Farenheit:" , temperatures_f)

Temperatures in Farenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
arr = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
arr

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
np.max(arr)

np.float64(26.1)

In [ ]:
np.min(arr)

np.float64(20.8)

In [ ]:
np.mean(arr)

np.float64(23.542857142857144)

In [ ]:
#4. Array Slicing and Indexing:
Extract the temperatures for the first three days of the week.
Extract the temperatures for the weekend (last two days).
Extract the temperatures for the middle three days of the week.

In [ ]:
temperature_w1

[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [ ]:
temperature_w1[:3]

[22.5, 25.3, 20.8]

In [ ]:
temperature_w1[-2:]

[24.8, 21.9]

In [ ]:
temperature_w1[2:5]

[20.8, 23.4, 26.1]

In [ ]:
#5. Create a 2D Array:
Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:
Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
Row 2: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 2)

In [ ]:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]])

In [ ]:
temperatures_2d = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] ])
temperatures_2d

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]])

In [ ]:
#6. Inspect and Slice the 2D Array:
Inspect and print the shape, data type, and total number of elements in the
temperatures array.
Extract the temperatures for each week and the weekends (last two days)
for both weeks.

In [ ]:
len(temperatures)

2

In [ ]:
temperatures.shape

(2, 7)

In [ ]:
temperatures.dtype

dtype('float64')

In [ ]:
temperatures[0]

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
temperatures[1]

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]])

In [ ]:
temperatures[:,-2:]

array([[24.8, 21.9],
       [24.8, 21.9]])

In [ ]:
import pandas as pd

In [ ]:
#Pandas Series:
1. Creating Pandas Series:
Create a Pandas Series named marks with the following data:
Marks: 95, 92, 89, 85, 80
Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [ ]:
s = [95, 92, 89, 85, 80]
Marks = pd.Series(s)
Marks

0    95
1    92
2    89
3    85
4    80
dtype: int64

In [ ]:
s = pd.Series([95, 92, 89, 85, 80] , index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
print(s)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
#2. Indexing and Slicing:
Use the integer index position to access the mark of the 1st rank student.
Use the loc accessor to retrieve the marks of the top 3 ranks by
specifying their index labels.
Use the iloc accessor to retrieve the mark of the 3rd rank student.
Apply a boolean mask to filter the Series and retrieve the ranks where the
marks are greater than 90.

In [ ]:
import pandas as pd
Marks = pd.Series([95, 92, 89, 85, 80] , index = ['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
Marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [ ]:
Marks[0]

/tmp/ipython-input-2988554515.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Marks[0]


np.int64(95)

In [ ]:
Marks.loc['Rank1':'Rank3']

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [ ]:
Marks.iloc[2]

np.int64(89)

In [ ]:
Marks>90

Rank1     True
Rank2     True
Rank3    False
Rank4    False
Rank5    False
dtype: bool

In [ ]:
#3. Manipulating Series:
Modify the mark of the student with the 1st rank to 100.
Remove the entry corresponding to the last rank from the Series.
Compute the CGPA by dividing each mark in the Series by 10.

In [ ]:
Marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [ ]:
Marks.loc['Rank1'] = 100

In [ ]:
Marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [ ]:
Marks.drop('Rank5')

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [ ]:
Marks = Marks / 10

In [ ]:
Marks

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Rank5     8.0
dtype: float64

In [ ]:
#Pandas DataFrame:
1. Creating Pandas DataFrame:
Create a Pandas DataFrame named transactions with the following data:
TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'
Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [1]:
import pandas as pd

In [81]:
transactions = pd.DataFrame({'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],'Amount':[ 200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})
print(transactions)



   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
#2. Data Exploration:
Display the transactions DataFrame and its basic information, including
head, tail, shape, column names, and data types.
Display only the 'ProductCategory' and 'Amount' columns.
Retrieve the last 3 columns of the DataFrame using iloc or loc.
Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
Find the value counts for the 'ProductCategory' column.
Find the unique values in the 'Region' column.
Group by 'Region' and find the mean amount for each region.

In [6]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   TransactionID    10 non-null     int64 
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [82]:
transactions.head()

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [9]:
transactions.tail()

TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [10]:
transactions.shape

(10, 4)

In [11]:
transactions.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [12]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [13]:
transactions[['ProductCategory','Amount']]

ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [20]:
transactions.loc[:,['ProductCategory', 'Region', 'Amount']]

ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [ ]:
#Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
Find the value counts for the 'ProductCategory' column.
Find the unique values in the 'Region' column.
Group by 'Region' and find the mean amount for each region.

In [25]:
transactions['Region'].nunique()

4

In [26]:
transactions['ProductCategory'].count()

np.int64(10)

In [27]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [ ]:
#3. Manipulating the DataFrame:
Modify the 'Amount' for the transaction with TransactionID 102 to 165.
Add a new column 'Discount' by calculating 10% of the 'Amount'.
Remove the row with TransactionID 109.
Delete the 'Discount' column from the DataFrame.

In [55]:
import pandas as pd

In [56]:
transactions = pd.DataFrame({'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
'South', 'North'],'Amount':[ 200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [88]:
transactions.loc[ 1 , 'Amount' ] = 165
transactions

TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      15.0
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [87]:
transactions[ 'Discount' ] = transactions[ 'Amount' ] * 0.10
transactions

TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     150      15.0
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [86]:
transactions.drop( 'Discount' , axis=1, inplace=True)
transactions

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [83]:
transactions.drop( 8 , axis=0, inplace=True)
transactions

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400